pipeline:
  backend:
    image: golang
    commands:
      - echo "backend testing"
      - go test
      - echo "build backend"
      - go build

  frontend:
    image: golang
    commands:
      - echo "frontend testing"

  deploy:
    image: golang
    commands:
      - echo "deploy"
    when:
      local: false
